services:
  # Postgres for Keycloak
  postgres_keycloak:
    image: postgres:latest
    container_name: postgres_keycloak
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - ./volumes/keycloak-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5436:5432"
    networks:
      - keycloak_network

  # Keycloak service for the expenses application
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    container_name: keycloak
    command:
      - start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres_keycloak
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_HEALTH_ENABLED: 'true'
      KEYCLOAK_LOG_LEVEL: DEBUG
    ports:
      - "8080:8080"
    depends_on:
      postgres_keycloak:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - keycloak_network
    restart: always

  # MongoDB for the expenses application
  mongo_database:
    image: mongo:latest
    container_name: mongo_database
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: expenses-management
    volumes:
      - ./volumes/mongo-qe:/data/db
    ports:
      - "27017:27017"
    networks:
      - ea_network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5

  # App service
  app:
    build:
      context: .
    container_name: expenses_app
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: mongodb://root:password@mongo_database:27017/expenses-management?authSource=admin
      KC_BASE_URL: http://keycloak:8080
      KC_WEB_CLIENT_ID: your_client_id
      KC_WEB_CLIENT_SECRET: your_client_secret
      KC_REALM: avonet
    depends_on:
      - postgres_keycloak
      - mongo_database
    networks:
      - ea_network

networks:
  keycloak_network:
    driver: bridge
  ea_network:
    driver: bridge
